[package]
name = "aws"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.52"
aws-sdk-ec2 = "0.22"
aws-sdk-eks = "0.22"
aws-types = "0.52"
