blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/clowdhaus/eksup/discussions/new/choose
    about: Ask a general question about eksup or upgrading EKS clusters
